export const TITLE_APP = "Bansos Covid-19";
export const META_DESC = "Bantuan sosial terdampak covid 19 di jawa barat";
export const TITLE_FORM = "Bantuan Sosial Covid-19";
export const DELAY_RESPONSE = 1500;
export const MESSAGE_SUCCESS_API = 'Data berhasil disimpan';
export const MESSAGE_FAILED_API = 'Data gagal disimpan';
export const TERM_OF_RESPONSIBILITY = "Saya menyatakan bahwa data yang diisikan adalah benar dan siap mempertanggungjawabkan apabila ditemukan ketidaksesuaian dalam data tersebut.";
export const URL_LINKEDIN = "https://www.linkedin.com/in/hegi-tri-saputra";
export const KEY_DATA = 'X-Data-Form';
export const MAX_SIZE_FILE = 2; // MB
export const LENGTH_NO_ID = 16;
export const SUPPORTED_FORMATS = ["image/jpg", "image/jpeg", "image/bmp", "image/png"];
